# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DIO service resources
email: thomas.jeffery@gov.ab.ca
description: > # this means to ignore newlines until "baseurl:"
  Design system, common services, and support for service teams.
baseurl: "/DIO-DS/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  twjeffery

# Build settings
markdown: kramdown

theme: jekyll-theme-slate

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/twjeffery/DIO-test-2" # the github URL for your repo
gh_edit_branch: "restore-better" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
